spring:
  profiles:
    active: local
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: example
            client-secret: example
            scope: example
app:
  jwt:
    jwt-secret-key: example
    jwt-expiration-in-ms: 31536000000
aws:
  access-key: example
  secret-key: example
  s3:
    endpoint: example
    bucket: example
    dir: example
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/stackoverflow?serverTimezone=UTC
    username: toy-stackoverflow
    password: stackoverflow
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
      # create: 시작 시 테이블 drop 후 재생성
      # update: 시작 시 자동 migrate
      # none: db 그대로
      # create-drop: 시작 시 테이블 create, 종료 시 drop
